### ISSUE TITLE
Just hangs

### ISSUE THREAD

**Issue by MaxPleaner** [zedapp/zedrem#20]
I first tried to start the Zed daemon with `zedd` - here's an issue relating to that: https://github.com/zedapp/zed/issues/585

I also tried `zedrem`, but it seems to just hang with no output.

I'm trying `zedrem` or `zedrem /some/dir` and both have no output and don't exit. I let it go about 5 minutes. Should I wait longer?

I'm running on a Ubuntu machine hosted in Nitrous.io

**Comment by efrecon** [comment]
Experiencing the same hang for `zedrem`, tried both the Windows and the Linux clients. No difference. I have waited and `remote.zedapp.org` seems to be responding to ping. However, trying to run the [Dark Web Socket Terminal](https://chrome.google.com/webstore/detail/dark-websocket-terminal/dmogdjmcpfaibncngoolgljgocdabhke) returns "No protocol negociation". Is there another open `zedrem` server somewhere?

**Comment by zefhemel** [comment]
Fixed.

**Comment by efrecon** [comment]
Thanks @zefhemel ! 

However, now, I cannot open the URL that is being printed out by `zedrem`, e.g. https://remote.zedapp.org:443/fs/xxxxxx. I have tried replacing it with `wss://`, but it doesn't help. Opening a new issue with this instead.
